<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ai_msc_robotics_assignments_ros</name>
  <version>0.9.0</version>
  <description>Doom can run anywhere. Now it runs on ROS too.</description>
  <maintainer email="gstavrinos@protonmail.com">rosez_user</maintainer>
  <license>GPL-2.0</license>

  <!-- <buildtool_depend>ament_cmake</buildtool_depend> -->
  <!-- <buildtool_depend>ament_cmake_python</buildtool_depend> -->

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>std_msgs</depend>
  <depend>nav2_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_python</build_type>
    <!-- <build_type>ament_cmake_python</build_type> -->
  </export>
</package>
